### ISSUE TITLE
ImportError: No module named 'SoapySDR'

### ISSUE THREAD

**Issue by FFY00** [pothosware/SoapySDR#143]
My build proccess.

```
anubis@FFY00:~/git/SoapySDR/build$ cmake .. -DUSE_PYTHON_CONFIG=ON
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- 
-- #############################################
-- ## Begin configuration for Python support...
-- #############################################
-- Enabling optional Python bindings if possible...
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
-- SWIG_FOUND: TRUE - 3.0.8
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- PYTHONINTERP_FOUND: TRUE - 2.7.12
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_INSTALL_DIR: ${prefix}/lib/python2.7/dist-packages
-- PYTHONLIBS_FOUND: TRUE - 2.7.12
-- PYTHON_INCLUDE_DIRS: /usr/include/python2.7;/usr/include/x86_64-linux-gnu/python2.7
-- PYTHON_LIBRARIES: -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
-- Performing Test SIZE_T_IS_UNSIGNED_INT
-- Performing Test SIZE_T_IS_UNSIGNED_INT - Failed
-- CMAKE_SWIG_FLAGS=-c++;-threads
-- 
-- #############################################
-- ## Begin configuration for Python3 support...
-- #############################################
-- Enabling optional Python3 bindings if possible...
-- SWIG_FOUND: TRUE - 3.0.8
-- Found Python3Interp: /usr/bin/python3  
-- Could NOT find Python3InterpDbg (missing:  PYTHON3_DBG_EXECUTABLE) 
-- PYTHON3INTERP_FOUND: TRUE
-- PYTHON3_EXECUTABLE: /usr/bin/python3
-- PYTHON3_INSTALL_DIR: ${prefix}/lib/python3/dist-packages
-- Found Python3Libs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so  
-- PYTHON3LIBS_FOUND: TRUE
-- PYTHON3_INCLUDE_DIRS: /usr/include/python3.5m
-- PYTHON3_LIBRARIES: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- CMAKE_SWIG_FLAGS=-c++;-threads
-- 
-- ######################################################
-- ## SoapySDR enabled features
-- ######################################################
-- 
 * Library , runtime library v0.6.1-gba9ad2d2
 * Tests , library unit tests
 * Docs , doxygen documentation
 * Python , python bindings v2.7.12
 * Python3 , python3 bindings

-- ######################################################
-- ## SoapySDR disabled features
-- ######################################################
-- 

-- SoapySDR version: v0.6.1-gba9ad2d2
-- ABI/so version: v0.6
-- Install prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anubis/git/SoapySDR/build
anubis@FFY00:~/git/SoapySDR/build$ make
Scanning dependencies of target docs
Scanning dependencies of target SoapySDR
[  2%] Generating documentation with doxygen
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Searching for files in directory /home/anubis/git/SoapySDR/include/SoapySDR
Reading and parsing tag files
Parsing files
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Config.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Config.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Config.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Config.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Constants.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Constants.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Device.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Device.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Device.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Device.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Errors.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Errors.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Errors.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Errors.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Formats.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Formats.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Formats.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Formats.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Logger.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Logger.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Logger.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Logger.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Modules.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Modules.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Modules.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Modules.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Registry.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Registry.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Time.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Time.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Time.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Time.hpp...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Types.h...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Types.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Types.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Types.hpp...
[  5%] Building CXX object lib/CMakeFiles/SoapySDR.dir/NullDevice.cpp.o
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Version.h...
[  8%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Factory.cpp.o
[ 13%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Errors.cpp.o
[ 13%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Types.cpp.o
[ 16%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Device.cpp.o
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Version.h...
Preprocessing /home/anubis/git/SoapySDR/include/SoapySDR/Version.hpp...
Parsing file /home/anubis/git/SoapySDR/include/SoapySDR/Version.hpp...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
[ 21%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Logger.cpp.o
[ 21%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Registry.cpp.o
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Creating members for template instances...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating code for file Config.h...
Generating code for file Config.hpp...
Generating code for file Constants.h...
Generating code for file Device.h...
Generating code for file Device.hpp...
[ 24%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Formats.cpp.o
Generating code for file Errors.h...
Generating code for file Errors.hpp...
Generating code for file Formats.h...
Generating code for file Formats.hpp...
Generating code for file Logger.h...
Generating code for file Logger.hpp...
Generating code for file Modules.h...
Generating code for file Modules.hpp...
Generating code for file Registry.hpp...
Generating code for file Time.h...
Generating code for file Time.hpp...
Generating code for file Types.h...
Generating code for file Types.hpp...
Generating code for file Version.h...
Generating code for file Version.hpp...
Generating file documentation...
Generating docs for file Config.h...
Generating docs for file Config.hpp...
Generating docs for file Constants.h...
Generating docs for file Device.h...
Generating docs for file Device.hpp...
Generating docs for file Errors.h...
Generating docs for file Errors.hpp...
Generating docs for file Formats.h...
Generating docs for file Formats.hpp...
Generating docs for file Logger.h...
Generating docs for file Logger.hpp...
Generating docs for file Modules.h...
Generating docs for file Modules.hpp...
Generating docs for file Registry.hpp...
Generating docs for file Time.h...
Generating docs for file Time.hpp...
Generating docs for file Types.h...
Generating docs for file Types.hpp...
Generating docs for file Version.h...
Generating docs for file Version.hpp...
Generating page documentation...
Generating docs for page deprecated...
Generating group documentation...
Generating class documentation...
Generating docs for compound SoapySDRArgInfo...
Generating docs for compound SoapySDRKwargs...
Generating docs for compound SoapySDRRange...
Generating namespace index...
Generating docs for namespace SoapySDR
Generating docs for compound SoapySDR::ArgInfo...
Generating docs for compound SoapySDR::Device...
[ 27%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Modules.cpp.o
Generating docs for compound SoapySDR::Range...
Generating docs for compound SoapySDR::Registry...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating graphical class hierarchy...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
Running dot...
Running dot for graph 1/1
[ 29%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Version.cpp.o
[ 32%] Building CXX object lib/CMakeFiles/SoapySDR.dir/TypesC.cpp.o
lookup cache used 582/65536 hits=3117 misses=587
finished...
[ 32%] Built target docs
[ 35%] Building CXX object lib/CMakeFiles/SoapySDR.dir/ModulesC.cpp.o
[ 37%] Building CXX object lib/CMakeFiles/SoapySDR.dir/VersionC.cpp.o
[ 40%] Building CXX object lib/CMakeFiles/SoapySDR.dir/DeviceC.cpp.o
[ 43%] Building CXX object lib/CMakeFiles/SoapySDR.dir/FactoryC.cpp.o
[ 45%] Building CXX object lib/CMakeFiles/SoapySDR.dir/LoggerC.cpp.o
[ 48%] Building CXX object lib/CMakeFiles/SoapySDR.dir/TimeC.cpp.o
[ 51%] Building CXX object lib/CMakeFiles/SoapySDR.dir/ErrorsC.cpp.o
[ 54%] Building CXX object lib/CMakeFiles/SoapySDR.dir/FormatsC.cpp.o
[ 56%] Linking CXX shared library libSoapySDR.so
[ 56%] Built target SoapySDR
Scanning dependencies of target SoapySDRUtil
Scanning dependencies of target TestFormatParser
Scanning dependencies of target TestTimeConversion
[ 59%] Swig source
Scanning dependencies of target TestKwargsMarkup
[ 62%] Swig source
[ 64%] Building CXX object tests/CMakeFiles/TestTimeConversion.dir/TestTimeConversion.cpp.o
[ 67%] Building CXX object tests/CMakeFiles/TestFormatParser.dir/TestFormatParser.cpp.o
[ 70%] Building CXX object tests/CMakeFiles/TestKwargsMarkup.dir/TestKwargsMarkup.cpp.o
[ 72%] Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapySDRUtil.cpp.o
[ 75%] Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapyRateTest.cpp.o
[ 78%] Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapySDRProbe.cpp.o
[ 81%] Linking CXX executable TestTimeConversion
[ 83%] Linking CXX executable TestFormatParser
[ 83%] Built target TestTimeConversion
[ 83%] Built target TestFormatParser
[ 86%] Linking CXX executable TestKwargsMarkup
[ 86%] Built target TestKwargsMarkup
[ 89%] Linking CXX executable SoapySDRUtil
[ 89%] Built target SoapySDRUtil
Scanning dependencies of target _SoapySDR
[ 91%] Building CXX object python/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o
Scanning dependencies of target _SoapySDR3
[ 94%] Building CXX object python3/CMakeFiles/_SoapySDR3.dir/SoapySDRPYTHON_wrap.cxx.o
[ 97%] Linking CXX shared module _SoapySDR.so
[ 97%] Built target _SoapySDR
[100%] Linking CXX shared module _SoapySDR.so
[100%] Built target _SoapySDR3
anubis@FFY00:~/git/SoapySDR/build$ sudo make install
[ 54%] Built target SoapySDR
[ 64%] Built target SoapySDRUtil
[ 70%] Built target TestFormatParser
[ 75%] Built target TestTimeConversion
[ 81%] Built target TestKwargsMarkup
[ 83%] Built target docs
[ 91%] Built target _SoapySDR
[100%] Built target _SoapySDR3
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/share/cmake/SoapySDR/SoapySDRConfig.cmake
-- Up-to-date: /usr/local/share/cmake/SoapySDR/SoapySDRUtil.cmake
-- Installing: /usr/local/share/cmake/SoapySDR/SoapySDRConfigVersion.cmake
-- Up-to-date: /usr/local/include/SoapySDR
-- Up-to-date: /usr/local/include/SoapySDR/Constants.h
-- Up-to-date: /usr/local/include/SoapySDR/Config.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Errors.h
-- Up-to-date: /usr/local/include/SoapySDR/Time.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Logger.h
-- Up-to-date: /usr/local/include/SoapySDR/Device.h
-- Up-to-date: /usr/local/include/SoapySDR/Logger.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Formats.h
-- Up-to-date: /usr/local/include/SoapySDR/Modules.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Formats.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Errors.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Version.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Modules.h
-- Up-to-date: /usr/local/include/SoapySDR/Registry.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Types.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Device.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Time.h
-- Up-to-date: /usr/local/include/SoapySDR/Config.h
-- Up-to-date: /usr/local/include/SoapySDR/Version.h
-- Up-to-date: /usr/local/include/SoapySDR/Types.h
-- Installing: /usr/local/lib/libSoapySDR.so.0.6.1
-- Up-to-date: /usr/local/lib/libSoapySDR.so.0.6
-- Up-to-date: /usr/local/lib/libSoapySDR.so
-- Installing: /usr/local/lib/pkgconfig/SoapySDR.pc
-- Installing: /usr/local/bin/SoapySDRUtil
-- Set runtime path of "/usr/local/bin/SoapySDRUtil" to ""
-- Up-to-date: /usr/local/share/man/man1/SoapySDRUtil.1
-- Installing: /usr/local/lib/python2.7/dist-packages/_SoapySDR.so
-- Set runtime path of "/usr/local/lib/python2.7/dist-packages/_SoapySDR.so" to ""
-- Installing: /usr/local/lib/python2.7/dist-packages/SoapySDR.py
-- Installing: /usr/local/lib/python3/dist-packages/_SoapySDR.so
-- Set runtime path of "/usr/local/lib/python3/dist-packages/_SoapySDR.so" to ""
-- Installing: /usr/local/lib/python3/dist-packages/SoapySDR.py
```

But when running `soapy_power` I get this.
```
Traceback (most recent call last):
  File "/home/anubis/.local/bin/soapy_power", line 7, in <module>
    from soapypower.__main__ import main
  File "/home/anubis/.local/lib/python3.5/site-packages/soapypower/__main__.py", line 5, in <module>
    import simplesoapy
  File "/home/anubis/.local/lib/python3.5/site-packages/simplesoapy.py", line 5, in <module>
    import SoapySDR
ImportError: No module named 'SoapySDR'
```

If I run it as a privileged user, I get.

```
Traceback (most recent call last):
  File "/usr/local/bin/soapy_power", line 9, in <module>
    load_entry_point('soapy-power==1.6.1', 'console_scripts', 'soapy_power')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/soapypower/__main__.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/simplesoapy.py", line 3, in <module>
ImportError: No module named abc
```

**Comment by guruofquality** [comment]
set the PYTHONPATH environment variable

**Comment by FFY00** [comment]
I already did that. I tried with both python 2 and 3 paths.

**Comment by guruofquality** [comment]
Do this: `python3 -c "import sys; print(sys.path)"` and see if the path contains /usr/local/lib/python3/dist-packages

The install path can also be overridden with -DPYTHON3_INSTALL_DIR=foo to cmake

**Comment by FFY00** [comment]
It does.

**Comment by FFY00** [comment]
Thanks, it's working.

**Comment by Dantali0n** [comment]
Would there be a way to better detect the sys path of python and automatically adjusting the PYTHON3_INSTALL_DIR as it seems that /usr/lib/pythonxx is the default on Arch based systems while the Soapy is installed into /usr/local/lib/pythonxx. 

This was at least my experience when using Manjaro 18.

**Comment by guruofquality** [comment]
> Would there be a way to better detect the sys path of python and automatically adjust the PYTHON3_INSTALL_DIR as it seems that /usr/lib/pythonxx is the default on Arch based systems while the Soapy is installed into /usr/local/lib/pythonxx.

I would check what site.getsitepackages() is showing. If there is no option to use /usr/local, thats unfortunate, but we still have the option of setting CMAKE_INSTALL_PREFIX, or setting PYTHONPATH, or an entry in an installed .pth file

**Comment by MartGro** [comment]
I was encountering the same error when trying to import SoapySDR in a conda environment. 
I solved it by adding the path to the library to the conda environment.
1)  `conda activate my_env`
2)` conda develop /usr/local/lib/python3.8/site-packages`  <-- path to the library. This is shown when running cmake

Then it works for me. I had to install conda-build beforehand (`conda install conda-build`)
