### ISSUE TITLE
Bug in Python bindings - can't uniquely select different AirSpy devices

### ISSUE THREAD

**Issue by billvoss** [pothosware/SoapySDR#292]
Hello,

I'm working on an application where I need to connect multiple SDRs of the same type (AirSpy R2). Each one has a different antenna so I need to be able to distinguish between them.

We can display connected devices with:
```
device_list = SoapySDR.Device.enumerate()
for device in device_list:
    print(device)
```

With two AirSpys connected this gives:
```
{device_id=0, driver=airspy, label=AIRSPY [260868c8:2673939b], serial=260868c8:2673939b}
{device_id=1, driver=airspy, label=AIRSPY [260868c8:266b479b], serial=260868c8:266b479b}
```
As in the C++ API, I want to be able to connect to a specific device i with:

`sdr = SoapySDR.Device(device_list[i])
`
This works for the first SDR with device_id=0. However, the next device crashes! As per:

```
Traceback (most recent call last):
  File "./multi_connect_test.py", line 36, in <module>
    sdr2 = SoapySDR.Device(args)
  File "/home/bill/miniforge3/envs/cusignal-dev/lib/python3.6/site-packages/SoapySDR.py", line 1926, in __new__
    return cls.make(*args, **kwargs)
RuntimeError: Airspy device_id out of range [0 .. 1].
```

I believe this is a bug in the Python binding. Something to do with the device_id being a string, but somewhere it is being checked again an int range?

Any advice on workarounds would be appreciated, or I'm happy to work together to fix the bug.

Thanks,
Bill

**Comment by guruofquality** [comment]
Honestly, something is probably wrong with the Airspy find and open functions. The device ID just some "internal" index that changes as soon as you open the first device.

Although it could be fixed, in my opinion, this device ID stuff has to go. It should use the open by serial convention. Since you have two airspy devices, I would greatly appreciate a PR that cleans up this stuff.

Just as an example, airspyhf does this:

* https://github.com/pothosware/SoapyAirspyHF/blob/master/Registration.cpp
* https://github.com/pothosware/SoapyAirspyHF/blob/master/Settings.cpp#L61

A plea in SDRPlay for open by serial: https://github.com/pothosware/SoapySDRPlay3/issues/23 (and its almost ready for merge)
